### ISSUE TITLE
"TypeError: resolvers is not iterable" when applying toJson on ApiObject

### ISSUE THREAD

**Issue by ProcopVladimirAlexandru** [cdk8s-team/cdk8s-core#1962]
### Description of the bug:

Method `toJson()` of objects of type `ApiObject` from `cdk8s` will throw the following exception unless the scope (of type `Construct`) of that `ApiObject` has a `resolvers: Array = [...]` property.

### Reproduction Steps:

Run the following Typescript code that is very basic K8s use case.

```
import { ApiObject, Chart } from 'cdk8s';

class CustomChart1 extends Chart {
    // public resolvers = [];  // TODO uncomment this to suppress resolvers exception
    public pod;
    public job;
    public constructor(
        public uid: string,
        public namespace: string
    ) {
        super(null, uid, { namespace: namespace, labels:  {}});
        this.pod = this.getPod();
        this.job = new ApiObject(this, this.uid, {
            apiVersion: 'batch/v1',
            kind: 'Job', 
            metadata: {
                labels: {},
                name: 'test-job-name-45631685',
                annotations: {},
            },
            spec: {
                template: {
                    metadata: {
                        labels: {},
                        annotations: {},
                    },
                    spec: {
                        ...this.pod,
                    },
                },
            },
        }).toJson();
    }
    protected getPod() {
        return {
            containers: [
            {
                    name: "testing-cdk8s-123456789",
                    image: "nginx"
                }
        ]
        };
    }
}
new CustomChart1("test-cdk8s-chart-123456789", "test-namespace");


```

### Error Log:

```

/home/me/Documents/proj/api/node_modules/cdk8s/src/api-object.ts:224
      throw new Error('Failed serializing construct at path '${this.node.path}' with name '${this.name}': ${e}');
            ^
Error: Failed serializing construct at path 'test-cdk8s-chart-123456789/test-cdk8s-chart-123456789' with name 'test-job-name-45631685': TypeError: resolvers is not iterable
    at ApiObject.toJson (/home/me/Documents/proj/api/node_modules/cdk8s/src/api-object.ts:224:13)
    at new CustomChart1 (/home/me/Documents/proj/api/cdk8s_bug_example.ts:43:12)
    
```

### Environment:

  - **Framework Version**: 2.68.10
  - **OS**: Linux Mint 20 Ulyana
  

### Other:

The bug was introduced with [this feature](https://github.com/cdk8s-team/cdk8s-core/pull/1573/files#) which has also introduced the issue [here](https://github.com/cdk8s-team/cdk8s-core/issues/1873) that I am ALSO encountering.
This feature has to be rolled back or speedily fixed. We consider versions since its merging broken.

I would have attempted a quick PR for this resolvers issue because replacing the line
`const resolvers = App.of(apiObject).resolvers;`  found [here](https://github.com/cdk8s-team/cdk8s-core/pull/1573/files#diff-6e17b8e79c75c75e3252f375e881d44b415de8e8fc949bcccea81e6a511945d9R92) with
`const resolvers = App.of(apiObject).resolvers || [ ];` would solve the bug

BUT I am also experiencing the **_can't render non-simple object_** from [here](https://github.com/cdk8s-team/cdk8s-core/issues/1873) so this fix would not suffice.

Thank you!

---

This is :bug: Bug Report

**Comment by ProcopVladimirAlexandru** [comment]
After searching for related issues across cdk8s' Slack channels, I found the following PR: [PR-1770](https://github.com/cdk8s-team/cdk8s-core/pull/1770) which solved our problems.
In the code sample, the line
`super(null, uid, { namespace: namespace, labels:  {}});`
should be
`super(new App(), uid, { namespace: namespace, labels:  {}});`
In other words, the _scope_ of the _Chart_ should not be _null_, but a cdk8s _App_ object instead.
It would be great if there was some sort of changelog for cdk8s that would document such usage changes.
Thank you, closing the issue.
